name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./FinancasParaCasais/FinancasParaCasais.Api

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
