# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - financas-para-casais

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    env:
      solution: ./FinancasParaCasais/FinancasParaCasais.sln
      api-project: ./FinancasParaCasais/FinancasParaCasais.Api/FinancasParaCasais.Api.csproj

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ${{env.solution}} --configuration Debug

      - name: dotnet publish
        run: dotnet publish ${{env.api-project}} -c Debug -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'financas-para-casais'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8501526D0D924D27A6D8BBAC99577B99 }}
          package: '${{env.DOTNET_ROOT}}/myapp'
